"""se corrige relación entre service rating y service qualifiers

Revision ID: 359bac3a54d0
Revises: 5fd920733666
Create Date: 2025-03-29 13:29:16.270880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359bac3a54d0'
down_revision = '5fd920733666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calificativo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'service_qualifiers', ['calificativo_id'], ['id_qualifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('calificativo_id')

    # ### end Alembic commands ###
