"""se agrega la columna confirmacion_contrasenia

Revision ID: 42c9935dd011
Revises: 359bac3a54d0
Create Date: 2025-03-29 21:11:03.530655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c9935dd011'
down_revision = '359bac3a54d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmacion_contrasenia', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('confirmacion_contrasenia')

    # ### end Alembic commands ###
