"""Sincronizando cambios de esquema

Revision ID: 7a444204d355
Revises: 42c9935dd011
Create Date: 2026-01-03 16:27:33.754612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a444204d355'
down_revision = '42c9935dd011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('feedback_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id_usuario'], ondelete='CASCADE')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('message_receiver_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('message_sender_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['receiver_id'], ['id_usuario'])
        batch_op.create_foreign_key(None, 'usuarios', ['sender_id'], ['id_usuario'])

    with op.batch_alter_table('monetization_management', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('monetization_management_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id_usuario'], ondelete='CASCADE')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notification_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('notification_sender_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['sender_id'], ['id_usuario'])
        batch_op.create_foreign_key(None, 'usuarios', ['user_id'], ['id_usuario'])

    with op.batch_alter_table('productos_catalogo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_publicacion', sa.Boolean(), nullable=True))
        batch_op.alter_column('precio',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('imagen_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('service_ratings', schema=None) as batch_op:
        batch_op.alter_column('comentary_hired_employer',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('comentary_employer_hired',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('service_ratings_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id_usuario'], ondelete='CASCADE')

    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('servicio_id_contratante_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('servicio_id_contratado_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('servicio_id_usuario_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_contratante'], ['id_usuario'])
        batch_op.create_foreign_key(None, 'usuarios', ['id_contratado'], ['id_usuario'])
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'])

    with op.batch_alter_table('usuario_servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_servicio', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('usuario_servicio_usuario_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('usuario_servicio_servicio_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'servicio', ['id_servicio'], ['id_servicio'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='CASCADE')
        batch_op.drop_column('servicio_id')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('servicio_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('usuario_servicio_servicio_id_fkey'), 'servicio', ['servicio_id'], ['id_servicio'])
        batch_op.create_foreign_key(batch_op.f('usuario_servicio_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id_usuario'])
        batch_op.drop_column('id_servicio')
        batch_op.drop_column('id_usuario')

    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('servicio_id_usuario_fkey'), 'usuario', ['id_usuario'], ['id_usuario'])
        batch_op.create_foreign_key(batch_op.f('servicio_id_contratado_fkey'), 'usuario', ['id_contratado'], ['id_usuario'])
        batch_op.create_foreign_key(batch_op.f('servicio_id_contratante_fkey'), 'usuario', ['id_contratante'], ['id_usuario'])

    with op.batch_alter_table('service_ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('service_ratings_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id_usuario'], ondelete='CASCADE')
        batch_op.alter_column('comentary_employer_hired',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('comentary_hired_employer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('productos_catalogo', schema=None) as batch_op:
        batch_op.alter_column('imagen_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('precio',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('estado_publicacion')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notification_sender_id_fkey'), 'usuario', ['sender_id'], ['id_usuario'])
        batch_op.create_foreign_key(batch_op.f('notification_user_id_fkey'), 'usuario', ['user_id'], ['id_usuario'])

    with op.batch_alter_table('monetization_management', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('monetization_management_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id_usuario'], ondelete='CASCADE')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('message_sender_id_fkey'), 'usuario', ['sender_id'], ['id_usuario'])
        batch_op.create_foreign_key(batch_op.f('message_receiver_id_fkey'), 'usuario', ['receiver_id'], ['id_usuario'])

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('feedback_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id_usuario'], ondelete='CASCADE')

    op.create_table('usuario',
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ciudad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('apellidos', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contrasenia', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confirmacion_contrasenia', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profesion', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cedula', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('celular', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pais_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('validate', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('black_list', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ciudad_id'], ['colombia.ciudad_id'], name=op.f('usuario_ciudad_id_fkey')),
    sa.PrimaryKeyConstraint('id_usuario', name=op.f('usuario_pkey')),
    sa.UniqueConstraint('cedula', name=op.f('usuario_cedula_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('correo', name=op.f('usuario_correo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
